name: Prueba
version: '${project.version}'
main: dev.mruniverse.oragenstaffchat.OrangeStaffChat
api-version: 1.16
authors: [ JustJustin ]
description: Este es un plugin de staff chat
depend:
  - PlaceholderAPI